### ISSUE TITLE
Diseño y explicación de la arquitectura solución

### ISSUE THREAD

**Issue by sigiandre** [sigiandre/TF-Atencion-Covid-Concurrente#6]
- Diseño y explicación de la arquitectura solución.

**Comment by JettTeixeira** [comment]
Arquitectura propuesta incialmente (@JettTeixeira  @sigiandre  @EgoPro1  @Nico-j-j ):

![arquitectura](https://user-images.githubusercontent.com/6015939/140667239-250d5924-9192-4a4a-ade7-8b80a81741c7.png)
